// src/routes/Kiosk.svelte
<script lang="ts">
import { Building2, Info, MapPin, Printer, Tv } from "@lucide/svelte/icons";
import { onMount } from "svelte";
import * as v from "valibot";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "$lib/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
} from "$lib/components/ui/dialog";
import { buildNomorAntrian, todayIso } from "$lib/queue";
import { navigate } from "$lib/router";
import { type Layanan, LayananSchema } from "$lib/schemas";
import { supabase } from "$lib/supabaseClient";

let daftarLayanan = $state<Layanan[]>([]);
let loading = $state(false);
let antrianTerakhir = $state("-");
let popupTerbuka = $state(false);
let nomorBaru = $state("");
let namaLayananBaru = $state("");

onMount(async () => {
	const { data, error } = await supabase
		.from("layanan")
		.select("*")
		.order("id_layanan", { ascending: true });
	if (error) {
		console.error("Gagal mengambil data layanan:", error);
		return;
	}
	const result = v.safeParse(v.array(LayananSchema), data);
	if (result.success) daftarLayanan = result.output;
});

async function handleAmbilAntrian(layanan: Layanan) {
	if (loading) return;
	loading = true;
	try {
		const today = todayIso();
		const { data: antrianHariIni, error: countError } = await supabase
			.from("antrian")
			.select("id_antrian", { count: "exact" })
			.eq("id_layanan", layanan.id_layanan)
			.gte("tanggal", today);
		if (countError) throw countError;

		const urutan = (antrianHariIni?.length ?? 0) + 1;
		const nomor = buildNomorAntrian(layanan.kode_huruf, urutan);

		const { error: insertError } = await supabase.from("antrian").insert([
			{
				nomor_antrian: nomor,
				id_layanan: layanan.id_layanan,
				status: "menunggu",
				tanggal: today,
			},
		]);
		if (insertError) throw insertError;

		antrianTerakhir = nomor;
		nomorBaru = nomor;
		namaLayananBaru = layanan.nama_layanan;
		popupTerbuka = true;
		setTimeout(() => {
			popupTerbuka = false;
		}, 4000);
	} catch (error) {
		console.error("Error saat ambil antrian:", error);
	} finally {
		loading = false;
	}
}
</script>

<div class="min-h-screen bg-slate-50 text-slate-800">
	<nav class="sticky top-0 z-50 flex items-center justify-between border-b border-slate-200 bg-white px-4 py-3 shadow-sm sm:px-6">
		<div class="flex items-center gap-3 sm:gap-4">
			<img src="/logoinsunmedal.png" alt="Logo" class="h-10 w-10 object-contain" />
			<div>
				<h1 class="text-lg font-bold text-slate-800 sm:text-xl">Pelayanan Terpadu</h1>
				<div class="flex items-center gap-1 text-xs text-slate-500 sm:text-sm">
					<MapPin class="size-3.5" />
					<span class="hidden sm:inline">Kantor Kelurahan Desa Talun</span>
					<span class="sm:hidden">Kelurahan Talun</span>
				</div>
			</div>
		</div>
		<button
			class="hidden items-center gap-2 rounded-lg border border-slate-200 bg-slate-100 px-4 py-2 font-medium text-slate-600 transition-colors hover:bg-slate-200 hover:text-emerald-700 sm:flex"
			onclick={() => navigate('/monitor')}
		>
			<Tv class="size-4.5" />
			<span>Lihat Monitor Display</span>
		</button>
	</nav>

	<main class="mx-auto max-w-7xl px-4 py-8 lg:py-12">
		<div class="grid grid-cols-1 gap-8 lg:grid-cols-12">
			<div class="flex flex-col gap-6 lg:col-span-7">
				<div>
					<h2 class="mb-2 text-3xl font-bold text-slate-900">Ambil Nomor Antrian</h2>
					<p class="text-slate-500">
						Silakan pilih jenis layanan sesuai keperluan Anda di bawah ini.
					</p>
				</div>

				{#if daftarLayanan.length === 0}
					<Card class="py-20">
						<CardContent class="flex flex-col items-center gap-4">
							<div class="size-10 animate-spin rounded-full border-4 border-emerald-500 border-t-transparent"></div>
							<p class="text-slate-400">Memuat layanan...</p>
						</CardContent>
					</Card>
				{:else}
					<div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
						{#each daftarLayanan as item (item.id_layanan)}
							<button
								class="group flex h-full flex-col gap-4 rounded-2xl border border-slate-100 bg-white p-6 text-left shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-xl disabled:opacity-70"
								disabled={loading}
								onclick={() => handleAmbilAntrian(item)}
							>
								<div class="flex items-start justify-between">
									<div class="flex size-14 items-center justify-center rounded-2xl bg-emerald-50 transition-colors group-hover:bg-emerald-600">
										<Printer class="size-7 text-emerald-600 transition-colors group-hover:text-white" />
									</div>
									<span class="text-4xl font-bold text-slate-100 transition-colors group-hover:text-emerald-50">
										{item.kode_huruf}
									</span>
								</div>
								<div>
									<h3 class="mb-1 text-lg font-bold text-slate-800 transition-colors group-hover:text-emerald-700">
										{item.nama_layanan}
									</h3>
									<p class="line-clamp-2 text-sm text-slate-500">{item.deskripsi}</p>
								</div>
							</button>
						{/each}
					</div>
				{/if}
			</div>

			<div class="flex flex-col gap-6 lg:col-span-5">
				<Card class="overflow-hidden">
					<CardHeader class="border-b border-emerald-100 bg-emerald-50/50 text-center">
						<CardTitle class="text-emerald-900">Nomor Terakhir Diambil</CardTitle>
						<p class="text-xs text-emerald-600/60">Baru saja dicetak</p>
					</CardHeader>
					<CardContent class="flex min-h-[200px] flex-col items-center justify-center gap-2">
						<span class="text-7xl font-bold tracking-tighter text-slate-900">
							{antrianTerakhir}
						</span>
						<div class="mt-6 flex gap-2 opacity-40">
							<div class="size-2 animate-bounce rounded-full bg-slate-400"></div>
							<div class="size-2 animate-bounce rounded-full bg-slate-400 [animation-delay:100ms]"></div>
							<div class="size-2 animate-bounce rounded-full bg-slate-400 [animation-delay:200ms]"></div>
						</div>
					</CardContent>
				</Card>

				<div class="relative overflow-hidden rounded-2xl bg-emerald-600 p-6 text-white shadow-lg shadow-emerald-200">
					<div class="relative z-10">
						<div class="mb-3 flex items-center gap-2 font-semibold opacity-90">
							<Info class="size-4.5" />
							<span>Jam Operasional</span>
						</div>
						<ul class="space-y-3 text-sm text-emerald-50">
							<li class="flex justify-between border-b border-emerald-500/30 pb-2">
								<span>Senin - Kamis</span>
								<span class="rounded bg-emerald-700/50 px-2 py-0.5 font-mono font-medium">
									08:00 - 15:00
								</span>
							</li>
							<li class="flex justify-between pt-1">
								<span>Jumat</span>
								<span class="rounded bg-emerald-700/50 px-2 py-0.5 font-mono font-medium">
									08:00 - 11:00
								</span>
							</li>
						</ul>
					</div>
					<div class="absolute -bottom-10 -right-10 size-32 rounded-full bg-white/10 blur-2xl"></div>
				</div>

				<div class="mt-4 block text-center sm:hidden">
					<button class="font-medium text-sm text-emerald-600 underline" onclick={() => navigate('/monitor')}>
						Lihat Monitor Display TV
					</button>
				</div>
			</div>
		</div>
	</main>

	<Dialog bind:open={popupTerbuka}>
		<DialogContent class="border-t-4 border-emerald-500 sm:max-w-md">
			<DialogHeader>
				<DialogTitle class="sr-only">Nomor Antrian Anda</DialogTitle>
				<DialogDescription class="sr-only">Nomor antrian berhasil dibuat</DialogDescription>
			</DialogHeader>
			<div class="flex flex-col items-center gap-2 py-4 text-center">
				<span class="text-sm text-slate-500">Nomor Antrian Anda</span>
				<span class="my-4 text-7xl font-bold tracking-widest text-emerald-600">{nomorBaru}</span>
				<div class="rounded-lg border border-emerald-100 bg-emerald-50 px-5 py-2 text-sm font-medium text-emerald-700">
					{namaLayananBaru}
				</div>
				<p class="mt-4 animate-pulse text-xs text-slate-400">Sedang mencetak struk...</p>
			</div>
		</DialogContent>
	</Dialog>

	<div class="flex items-center justify-center gap-2 pb-6 text-xs text-slate-400">
		<Building2 class="size-3.5" />
		<span>&copy; 2026 Ujikom SMKN 1 Sumedang</span>
	</div>
</div>

// src/pages/public/Kiosk.jsx
import { useState, useEffect } from "react";
import { supabase } from "../../lib/supabaseClient";
import Swal from "sweetalert2";
import { Printer, MapPin, Building2, Info, Tv } from "lucide-react"; // Tambah icon Tv
import { Link } from "react-router-dom"; // Tambah Link untuk navigasi

export default function Kiosk() {
  const [loading, setLoading] = useState(false);
  const [daftarLayanan, setDaftarLayanan] = useState([]);
  const [antrianTerakhir, setAntrianTerakhir] = useState("-");

  // --- 1. Ambil Data Layanan ---
  useEffect(() => {
    const fetchLayanan = async () => {
      try {
        const { data, error } = await supabase
          .from("layanan")
          .select("*")
          .order("id_layanan", { ascending: true });

        if (error) throw error;
        if (data) setDaftarLayanan(data);
      } catch (err) {
        console.error("Gagal mengambil data layanan:", err);
      }
    };

    fetchLayanan();
  }, []);

  // --- 2. Fungsi Ambil Nomor Antrian ---
  const handleAmbilAntrian = async (layanan) => {
    if (loading) return;
    setLoading(true);

    try {
      const today = new Date().toISOString().split("T")[0];

      // Hitung jumlah antrian hari ini
      const { data: antrianHariIni, error: countError } = await supabase
        .from("antrian")
        .select("id_antrian", { count: "exact" })
        .eq("id_layanan", layanan.id_layanan)
        .gte("tanggal", today); // Pastikan filter tanggal benar

      if (countError) throw countError;

      // Generate Nomor Baru
      const urutan = (antrianHariIni?.length || 0) + 1;
      const nomorBaru = `${layanan.kode_huruf}-${String(urutan).padStart(3, "0")}`;

      // Simpan ke Database
      const { error: insertError } = await supabase.from("antrian").insert([
        {
          nomor_antrian: nomorBaru,
          id_layanan: layanan.id_layanan,
          status: "menunggu",
          tanggal: today,
        },
      ]);

      if (insertError) throw insertError;

      // Update Tampilan Mini Monitor
      setAntrianTerakhir(nomorBaru);

      // Tampilkan Popup Sukses
      await Swal.fire({
        title: "Berhasil!",
        html: `
          <div class="flex flex-col items-center gap-2">
            <span class="text-slate-500 text-sm">Nomor Antrian Anda</span>
            <span class="text-7xl font-bold text-emerald-600 tracking-widest my-4">${nomorBaru}</span>
            <div class="px-5 py-2 bg-emerald-50 text-emerald-700 rounded-lg text-sm font-medium border border-emerald-100">
              ${layanan.nama_layanan}
            </div>
            <p class="text-xs text-slate-400 mt-4 animate-pulse">Sedang mencetak struk...</p>
          </div>
        `,
        timer: 4000,
        timerProgressBar: true,
        showConfirmButton: false,
        background: "#fff",
        customClass: {
          popup: "rounded-2xl shadow-2xl p-6 border-t-4 border-emerald-500",
        },
      });
    } catch (error) {
      console.error("Error saat ambil antrian:", error);
      Swal.fire({
        icon: "error",
        title: "Gagal",
        text: "Terjadi kesalahan sistem. Silakan coba lagi.",
        confirmButtonColor: "#059669",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F3F4F6] text-slate-800 font-sans selection:bg-emerald-100">
      {/* --- NAVBAR UTAMA --- */}
      <nav className="bg-white border-b border-slate-200 px-4 sm:px-6 py-3 flex justify-between items-center sticky top-0 z-50 shadow-sm">
        {/* Kiri: Logo & Identitas */}
        <div className="flex items-center gap-3 sm:gap-4">
          <img
            src="/logoinsunmedal.png"
            alt="Logo"
            className="w-10 h-10 object-contain"
          />
          <div>
            <h1 className="text-lg sm:text-xl font-bold text-slate-800">
              Pelayanan Terpadu
            </h1>
            <div className="flex items-center gap-1 text-slate-500 text-xs sm:text-sm">
              <MapPin size={14} />
              <span className="hidden sm:inline">
                Kantor Kelurahan Desa Talun
              </span>
              <span className="sm:hidden">Kelurahan Talun</span>
            </div>
          </div>
        </div>

        {/* Kanan: Tombol Link ke Monitor TV */}
        <Link
          to="/monitor"
          target="_blank"
          className="hidden sm:flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-600 hover:text-emerald-700 px-4 py-2 rounded-lg font-medium transition-all duration-200 border border-slate-200"
        >
          <Tv size={18} />
          <span>Lihat Monitor Display</span>
        </Link>
      </nav>

      {/* --- KONTEN UTAMA --- */}
      <main className="max-w-7xl mx-auto px-4 py-8 lg:py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* BAGIAN KIRI: PILIH LAYANAN (7 Kolom) */}
          <div className="lg:col-span-7 flex flex-col gap-6">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 mb-2">
                Ambil Nomor Antrian
              </h2>
              <p className="text-slate-500">
                Silakan pilih jenis layanan sesuai keperluan Anda di bawah ini.
              </p>
            </div>

            {/* Loading State */}
            {daftarLayanan.length === 0 ? (
              <div className="text-center py-20 bg-white rounded-2xl shadow-sm border border-slate-100">
                <div className="animate-spin w-10 h-10 border-4 border-emerald-500 border-t-transparent rounded-full mx-auto mb-4"></div>
                <p className="text-slate-400">Memuat layanan...</p>
              </div>
            ) : (
              /* Grid Tombol Layanan */
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                {daftarLayanan.map((item) => (
                  <button
                    key={item.id_layanan}
                    onClick={() => handleAmbilAntrian(item)}
                    disabled={loading}
                    className="group relative bg-white p-6 rounded-2xl border border-slate-100 shadow-sm hover:shadow-xl hover:border-emerald-200 hover:-translate-y-1 transition-all duration-300 text-left flex flex-col gap-4 h-full"
                  >
                    <div className="flex justify-between items-start">
                      <div className="w-14 h-14 bg-emerald-50 rounded-2xl flex items-center justify-center group-hover:bg-emerald-600 transition-colors duration-300">
                        <Printer
                          className="text-emerald-600 group-hover:text-white transition-colors duration-300"
                          size={28}
                        />
                      </div>
                      <span className="text-4xl font-bold text-slate-100 group-hover:text-emerald-50 transition-colors duration-300">
                        {item.kode_huruf}
                      </span>
                    </div>

                    <div>
                      <h3 className="text-lg font-bold text-slate-800 mb-1 group-hover:text-emerald-700">
                        {item.nama_layanan}
                      </h3>
                      <p className="text-sm text-slate-500 line-clamp-2">
                        {item.deskripsi}
                      </p>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* BAGIAN KANAN: STATUS MINI (5 Kolom) */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            {/* Card Status Utama */}
            <div className="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden">
              <div className="bg-emerald-50/50 p-6 border-b border-emerald-100 text-center">
                <h3 className="text-emerald-900 font-semibold">
                  Nomor Terakhir Diambil
                </h3>
                <p className="text-emerald-600/60 text-xs mt-1">
                  Baru saja dicetak
                </p>
              </div>

              <div className="p-10 flex flex-col items-center justify-center gap-2 bg-white min-h-[200px]">
                <span className="text-7xl font-bold text-slate-900 tracking-tighter">
                  {antrianTerakhir}
                </span>
                <div className="flex gap-2 mt-6 opacity-40">
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce delay-100"></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce delay-200"></div>
                </div>
              </div>
            </div>

            {/* Jam Operasional */}
            <div className="bg-emerald-600 rounded-2xl p-6 text-white shadow-lg shadow-emerald-200 relative overflow-hidden">
              <div className="relative z-10">
                <div className="flex items-center gap-2 mb-3 opacity-90">
                  <Info size={18} />
                  <span className="font-semibold">Jam Operasional</span>
                </div>
                <ul className="space-y-3 text-emerald-50 text-sm">
                  <li className="flex justify-between border-b border-emerald-500/30 pb-2">
                    <span>Senin - Kamis</span>
                    <span className="font-mono font-medium bg-emerald-700/50 px-2 py-0.5 rounded">
                      08:00 - 15:00
                    </span>
                  </li>
                  <li className="flex justify-between pt-1">
                    <span>Jumat</span>
                    <span className="font-mono font-medium bg-emerald-700/50 px-2 py-0.5 rounded">
                      08:00 - 11:00
                    </span>
                  </li>
                </ul>
              </div>
              <div className="absolute -bottom-10 -right-10 w-32 h-32 bg-white/10 rounded-full blur-2xl"></div>
            </div>

            {/* Link Tambahan Mobile (Muncul cuma di HP) */}
            <div className="block sm:hidden text-center mt-4">
              <Link
                to="/monitor"
                className="text-emerald-600 font-medium text-sm underline"
              >
                Lihat Monitor Display TV
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
